version: '2'
services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #    - "8080:8080"
  #   volumes:
  #      - ./frontend:/app
  #      - /app/node_modules
  backend:
    build: ./backend
    ports:
     - "3000:3000"
    volumes:
       - ./backend:/app
       - /app/node_modules
  redis:
    image: redis:3.2.5-alpine